{
  "name": "retry-again",
  "version": "1.5.0",
  "description": "Retry function execution N ms later, controlled by try/catch error events, just new Retry(funct)",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fantasyui-com/retry-again.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/fantasyui-com/retry-again/issues"
  },
  "homepage": "https://github.com/fantasyui-com/retry-again#readme"
}
