{
  "name": "retry-again",
  "version": "1.10.0",
  "description": "Retry function execution N ms later, controlled by try/catch error events, just new Retry(funct)",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "save": "git add .; git commit -m 'New Release'; git push; npm version patch; npm publish; git push;"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fantasyui-com/retry-again.git"
  },
  "keywords": [],
  "author": "fantasyui.com <fantasyui.com@gmail.com>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/fantasyui-com/retry-again/issues"
  },
  "homepage": "https://github.com/fantasyui-com/retry-again#readme"
}
